spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: testdisk1110@gmail.com
    password: "lcbk silq oexu laom"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  redis:
    data:
      host: localhost
      port: 6379